### ISSUE TITLE
Issue Setting States for a CompositeNode with Dropout

### ISSUE THREAD

**Issue by liamb315** [sharadmv/deepx#26]
There seems to be an issue setting the state of a CompositeNode when there is Dropout.  For instance, previously I would save the parameters of a discriminator model defined as,

`discriminator = Sequence(Vector(len(text_encoding), batch_size=100)) >> Repeat(dropout_lstm, 2) >> Softmax(2)`

And then load them into a discriminator defined as,

`discriminator = Sequence(Vector(len(text_encoding_D))) >> (Repeat(LSTM(1024), 2) >> Softmax(2))`

(Notice the extra parenthesis which was used for when constructing the gan model).  However, when I do an identical procedure 

`discriminator = Sequence(Vector(len(text_encoding_D))) >> (Repeat(LSTM(1024) >> Dropout(0.5), 2) >> Softmax(2))
`

This fails with error message seen below.
## **Error Message**

AttributeError                            Traceback (most recent call last)
/usr/lib/python2.7/dist-packages/IPython/utils/py3compat.pyc in execfile(fname, *where)
    202             else:
    203                 filename = fname
--> 204             **builtin**.execfile(filename, *where)

/home/wfedus/projects/CharacterGAN/gan.py in <module>()
    128     # with open('models/discriminative/discriminative-model-3.0.1.pkl', 'rb') as fp:
    129     with open('models/discriminative/discriminative-dropout-model-0.0.1_lr0.001.pkl', 'rb') as fp:
--> 130         discriminator.set_state(pickle.load(fp))
    131 
    132 

/home/wfedus/projects/deepx/deepx/node/node.pyc in set_state(self, state)
    453     def set_state(self, state):
    454         left_state, right_state = state
--> 455         self.left.set_state(left_state)
    456         self.right.set_state(right_state)
    457 

/home/wfedus/projects/deepx/deepx/node/node.pyc in set_state(self, state)
    205     def set_state(self, state):
    206         assert self.is_initialized(), "Cannot set state of uninitialized node."
--> 207         for name, val in state.items():
    208             T.set_value(self.parameters[name], val)
    209 

AttributeError: 'tuple' object has no attribute 'items'

**Comment by sharadmv** [comment]
I don't think I'm following exactly what's happening.

You shouldn't be able to load state from a dropout LSTM into a normal LSTM.
