### ISSUE TITLE
Add mechanism for, e.g., tracking validation performance during training

### ISSUE THREAD

**Issue by turambar** [sharadmv/deepx#3]
We need a convenient way to call arbitrary functions during training. For example, I like to compute and compare validation performance for early stopping. I also like to save the model every so often, for good measure.

I like the way keras does this: the trainer can take a list of Callbacks (that have methods like on_iteration_end, on_epoch_end, etc. etc.). Perhaps we can do something similar. Alternatively, I can just make a trainer subclass?

I am happy to propose a design and then implement.

ALSO: if I want to delineate training by epoch (rather than merely counting iterations), what's the best way to achieve this? Should I subclass Trainer for this?

**Comment by sharadmv** [comment]
Everything that's in the ``dataset'' and ``train'' folders is up for rewriting. It's all just the stuff I used for beermind and I didn't really think about generalization. 

So, yes, that would be great!

I think delineating by epochs is fine, but I like training on a small set of batches just to verify that everything is working so maybe a different method (`train_iter` or `train_iterations`?). Feel free to rewrite trainer if you want.

**Comment by turambar** [comment]
Sweet. I'll look into it over the next few days.
