### ISSUE TITLE
TypeError: 'CompositeNode' object is not callable

### ISSUE THREAD

**Issue by sskgit** [sharadmv/deepx#30]
System:
Mac OS El Capitan
Python: 2.7 (Conda)

Installed DeepX and while running Quick Start example received error

>>> mlp(np.ones((10, 784)))
TypeError: 'CompositeNode' object is not callable

Did not find much information on this error.

Any thoughts on how to fix this issue?

Thanks

**Comment by sharadmv** [comment]
Ah sorry. Currently revising a lot of issues with the library. There will be a fix out in the next few weeks :).

**Comment by sskgit** [comment]
Thanks @sharadmv . Looking forward to it.
